/**
 * Coach Debrief — the first conversation after the workout.
 * Rendered right after the session is saved; generated by the AI coach.
 */
import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Button } from "@/components/ui/button";
import { Loader2, Share2, Sparkles, Droplets, Apple, Moon, Target, Users } from "lucide-react";
import { generateCoachDebrief } from "@/lib/coach-debrief.functions";
import type { CoachDebriefResult } from "@/lib/coach-debrief-safety";

export const Route = createFileRoute("/_authenticated/workouts/session/$sessionId/debrief/")({
  component: DebriefPage,
});

function DebriefPage() {
  const { sessionId } = Route.useParams();
  const run = useServerFn(generateCoachDebrief);

  const q = useQuery({
    queryKey: ["coach-debrief", sessionId],
    staleTime: Infinity,
    retry: false,
    // The server rebuilds the whole debrief context itself from sessionId
    // (Codex re-review round 2, blocker 3) — the client no longer builds
    // or sends it.
    queryFn: () => run({ data: { sessionId } }),
  });

  const result: CoachDebriefResult | undefined = q.data;
  const d = result?.status === "ok" ? result.debrief : null;
  const failure = result && result.status === "error" ? result : null;

  return (
    <div dir="rtl" className="mx-auto max-w-md space-y-4 py-4">
      <div className="surface-card space-y-2 p-5">
        <div className="flex items-center gap-2 text-primary">
          <Sparkles className="h-5 w-5" />
          <p className="text-[11px] font-semibold uppercase tracking-wider">תחקיר מאמן</p>
        </div>

        {q.isLoading && (
          <div className="flex items-center gap-2 py-4 text-sm text-muted-foreground">
            <Loader2 className="h-4 w-4 animate-spin" />
            המאמן עובר על האימון שלך…
          </div>
        )}

        {(q.isError || failure) && (
          <div className="space-y-2 py-3" role="alert">
            <p className="text-sm text-muted-foreground">
              לא הצלחתי להפיק תחקיר כרגע. הנתונים של האימון נשמרו במלואם.
            </p>
            {failure && (
              <div className="space-y-1 text-xs text-muted-foreground/70">
                <p>{failure.message}</p>
                <p>
                  מזהה תקלה: <bdi dir="ltr">{failure.correlationId}</bdi>
                </p>
              </div>
            )}
            <Button size="sm" variant="outline" onClick={() => q.refetch()}>
              נסה שוב
            </Button>
          </div>
        )}

        {d && (
          <>
            <h1 className="text-xl font-extrabold leading-snug">{d.greeting}</h1>
            {d.paragraphs.map((p, i) => (
              <p key={i} className="text-sm leading-relaxed text-muted-foreground">
                {p}
              </p>
            ))}
          </>
        )}
      </div>

      {d && d.highlights.length > 0 && (
        <div className="surface-card space-y-2 p-4">
          {d.highlights.map((h, i) => (
            <p key={i} className="flex items-start gap-2 text-sm font-medium">
              <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
              {h}
            </p>
          ))}
        </div>
      )}

      {d && (
        <div className="space-y-2">
          <Advice icon={<Moon className="h-4 w-4" />} text={d.recovery} label="התאוששות" />
          <Advice icon={<Apple className="h-4 w-4" />} text={d.nutrition} label="תזונה" />
          <Advice icon={<Droplets className="h-4 w-4" />} text={d.hydration} label="שתייה" />
          <Advice icon={<Target className="h-4 w-4" />} text={d.nextFocus} label="האימון הבא" />
        </div>
      )}

      {q.isLoading ? (
        <Button size="lg" variant="outline" className="h-12 w-full text-base" disabled>
          <Loader2 className="ml-2 h-4 w-4 animate-spin" />
          ממתין לתחקיר המאמן…
        </Button>
      ) : (
        <div className="flex gap-2 w-full">
          {/* Available even when the debrief failed — AI is never a
              precondition for sharing the workout itself. */}
          <Button asChild size="lg" variant="outline" className="h-12 flex-1 text-base">
            <Link to="/workouts/session/$sessionId/debrief/share" params={{ sessionId }}>
              <Users className="ml-2 h-4 w-4" />
              שתף בקהילה
            </Link>
          </Button>
          <Button asChild size="lg" variant="outline" className="h-12 flex-1 text-base">
            <Link to="/workouts/session/$sessionId/debrief/export" params={{ sessionId }}>
              <Share2 className="ml-2 h-4 w-4" />
              ייצוא אימון כטקסט
            </Link>
          </Button>
        </div>
      )}

      <Button asChild size="lg" className="h-14 w-full text-lg">
        <Link to="/history" search={{ tab: "workouts" }}>
          סיום
        </Link>
      </Button>
    </div>
  );
}

function Advice({
  icon,
  text,
  label,
}: {
  icon: React.ReactNode;
  text: string | null;
  label: string;
}) {
  if (!text) return null;
  return (
    <div className="surface-card flex items-start gap-3 p-4">
      <span className="mt-0.5 text-primary">{icon}</span>
      <div className="min-w-0">
        <p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p>
        <p className="text-sm leading-relaxed">{text}</p>
      </div>
    </div>
  );
}
