/**
 * Coach Debrief — the first conversation after the workout.
 * Rendered right after the session is saved; generated by the AI coach.
 */
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Button } from "@/components/ui/button";
import { Loader2, Share2, Sparkles, Droplets, Apple, Moon, Target } from "lucide-react";
import { buildDebriefContext } from "@/lib/coach-debrief";
import { generateCoachDebrief } from "@/lib/coach-debrief.functions";
import { fetchLifeProfile } from "@/lib/life-profile";

export const Route = createFileRoute("/_authenticated/workouts/session/$sessionId/debrief")({
  component: DebriefPage,
});

function DebriefPage() {
  const { sessionId } = Route.useParams();
  const navigate = useNavigate();
  const run = useServerFn(generateCoachDebrief);

  const q = useQuery({
    queryKey: ["coach-debrief", sessionId],
    staleTime: Infinity,
    retry: false,
    queryFn: async () => {
      const profile = await fetchLifeProfile().catch(() => null);
      const ctx = await buildDebriefContext(sessionId, profile?.first_name ?? "");
      return run({ data: ctx });
    },
  });

  const d = q.data;

  return (
    <div dir="rtl" className="mx-auto max-w-md space-y-4 py-4">
      <div className="surface-card space-y-2 p-5">
        <div className="flex items-center gap-2 text-primary">
          <Sparkles className="h-5 w-5" />
          <p className="text-[11px] font-semibold uppercase tracking-wider">תחקיר מאמן</p>
        </div>

        {q.isLoading && (
          <div className="flex items-center gap-2 py-4 text-sm text-muted-foreground">
            <Loader2 className="h-4 w-4 animate-spin" />
            המאמן עובר על האימון שלך…
          </div>
        )}

        {q.isError && (
          <p className="py-3 text-sm text-muted-foreground">
            לא הצלחתי להפיק תחקיר כרגע. הנתונים של האימון נשמרו במלואם.
          </p>
        )}

        {d && (
          <>
            <h1 className="text-xl font-extrabold leading-snug">{d.greeting}</h1>
            {d.paragraphs.map((p, i) => (
              <p key={i} className="text-sm leading-relaxed text-muted-foreground">
                {p}
              </p>
            ))}
          </>
        )}
      </div>

      {d && d.highlights.length > 0 && (
        <div className="surface-card space-y-2 p-4">
          {d.highlights.map((h, i) => (
            <p key={i} className="flex items-start gap-2 text-sm font-medium">
              <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
              {h}
            </p>
          ))}
        </div>
      )}

      {d && (
        <div className="space-y-2">
          <Advice icon={<Moon className="h-4 w-4" />} text={d.recovery} label="התאוששות" />
          <Advice icon={<Apple className="h-4 w-4" />} text={d.nutrition} label="תזונה" />
          <Advice icon={<Droplets className="h-4 w-4" />} text={d.hydration} label="שתייה" />
          <Advice icon={<Target className="h-4 w-4" />} text={d.nextFocus} label="האימון הבא" />
        </div>
      )}

      <Button
        size="lg"
        variant="outline"
        className="h-12 w-full text-base"
        disabled={q.isLoading}
        onClick={() =>
          navigate({ to: "/workouts/session/$sessionId/debrief/export", params: { sessionId } })
        }
      >
        {q.isLoading ? (
          <Loader2 className="ml-2 h-4 w-4 animate-spin" />
        ) : (
          <Share2 className="ml-2 h-4 w-4" />
        )}
        {q.isLoading ? "ממתין לתחקיר המאמן…" : "ייצוא אימון כטקסט"}
      </Button>

      <Button
        size="lg"
        className="h-14 w-full text-lg"
        onClick={() => navigate({ to: "/workouts/history" })}
      >
        סיום
      </Button>
    </div>
  );
}

function Advice({
  icon,
  text,
  label,
}: {
  icon: React.ReactNode;
  text: string | null;
  label: string;
}) {
  if (!text) return null;
  return (
    <div className="surface-card flex items-start gap-3 p-4">
      <span className="mt-0.5 text-primary">{icon}</span>
      <div className="min-w-0">
        <p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p>
        <p className="text-sm leading-relaxed">{text}</p>
      </div>
    </div>
  );
}
