/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkoutsRouteImport } from './routes/_authenticated/workouts'
import { Route as AuthenticatedWorkoutTemplatesRouteImport } from './routes/_authenticated/workout-templates'
import { Route as AuthenticatedShiftRouteImport } from './routes/_authenticated/shift'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedMediaInboxRouteImport } from './routes/_authenticated/media-inbox'
import { Route as AuthenticatedMealsRouteImport } from './routes/_authenticated/meals'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedHydrationRouteImport } from './routes/_authenticated/hydration'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedDevRouteImport } from './routes/_authenticated/dev'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExercisesRouteImport } from './routes/_authenticated/exercises'
import { Route as AuthenticatedCaptureRouteImport } from './routes/_authenticated/capture'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedWorkoutsIndexRouteImport } from './routes/_authenticated/workouts.index'
import { Route as AuthenticatedDevIndexRouteImport } from './routes/_authenticated/dev.index'
import { Route as AuthenticatedWorkoutsProgramRouteImport } from './routes/_authenticated/workouts.program'
import { Route as AuthenticatedWorkoutsHistoryRouteImport } from './routes/_authenticated/workouts.history'
import { Route as AuthenticatedWorkoutSessionWorkoutIdRouteImport } from './routes/_authenticated/workout-session.$workoutId'
import { Route as AuthenticatedDevMediaRouteImport } from './routes/_authenticated/dev.media'
import { Route as AuthenticatedDevCharactersRouteImport } from './routes/_authenticated/dev.characters'
import { Route as AuthenticatedDevAssetsRouteImport } from './routes/_authenticated/dev.assets'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedWorkoutsSessionSessionIdRouteImport } from './routes/_authenticated/workouts.session.$sessionId'
import { Route as AuthenticatedWorkoutsHistorySessionIdRouteImport } from './routes/_authenticated/workouts.history.$sessionId'
import { Route as AuthenticatedWorkoutsSessionSessionIdIndexRouteImport } from './routes/_authenticated/workouts.session.$sessionId.index'
import { Route as AuthenticatedWorkoutsSessionSessionIdSummaryRouteImport } from './routes/_authenticated/workouts.session.$sessionId.summary'
import { Route as AuthenticatedWorkoutsSessionSessionIdDebriefRouteImport } from './routes/_authenticated/workouts.session.$sessionId.debrief'
import { Route as AuthenticatedWorkoutsSessionSessionIdBriefRouteImport } from './routes/_authenticated/workouts.session.$sessionId.brief'
import { Route as AuthenticatedWorkoutsSessionSessionIdExerciseExerciseIdRouteImport } from './routes/_authenticated/workouts.session.$sessionId.exercise.$exerciseId'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutsRoute = AuthenticatedWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkoutTemplatesRoute =
  AuthenticatedWorkoutTemplatesRouteImport.update({
    id: '/workout-templates',
    path: '/workout-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShiftRoute = AuthenticatedShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaInboxRoute = AuthenticatedMediaInboxRouteImport.update({
  id: '/media-inbox',
  path: '/media-inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMealsRoute = AuthenticatedMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHydrationRoute = AuthenticatedHydrationRouteImport.update({
  id: '/hydration',
  path: '/hydration',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevRoute = AuthenticatedDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExercisesRoute = AuthenticatedExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaptureRoute = AuthenticatedCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedWorkoutsIndexRoute =
  AuthenticatedWorkoutsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkoutsRoute,
  } as any)
const AuthenticatedDevIndexRoute = AuthenticatedDevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDevRoute,
} as any)
const AuthenticatedWorkoutsProgramRoute =
  AuthenticatedWorkoutsProgramRouteImport.update({
    id: '/program',
    path: '/program',
    getParentRoute: () => AuthenticatedWorkoutsRoute,
  } as any)
const AuthenticatedWorkoutsHistoryRoute =
  AuthenticatedWorkoutsHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedWorkoutsRoute,
  } as any)
const AuthenticatedWorkoutSessionWorkoutIdRoute =
  AuthenticatedWorkoutSessionWorkoutIdRouteImport.update({
    id: '/workout-session/$workoutId',
    path: '/workout-session/$workoutId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevMediaRoute = AuthenticatedDevMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedDevRoute,
} as any)
const AuthenticatedDevCharactersRoute =
  AuthenticatedDevCharactersRouteImport.update({
    id: '/characters',
    path: '/characters',
    getParentRoute: () => AuthenticatedDevRoute,
  } as any)
const AuthenticatedDevAssetsRoute = AuthenticatedDevAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedDevRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutsSessionSessionIdRoute =
  AuthenticatedWorkoutsSessionSessionIdRouteImport.update({
    id: '/session/$sessionId',
    path: '/session/$sessionId',
    getParentRoute: () => AuthenticatedWorkoutsRoute,
  } as any)
const AuthenticatedWorkoutsHistorySessionIdRoute =
  AuthenticatedWorkoutsHistorySessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedWorkoutsHistoryRoute,
  } as any)
const AuthenticatedWorkoutsSessionSessionIdIndexRoute =
  AuthenticatedWorkoutsSessionSessionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkoutsSessionSessionIdRoute,
  } as any)
const AuthenticatedWorkoutsSessionSessionIdSummaryRoute =
  AuthenticatedWorkoutsSessionSessionIdSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => AuthenticatedWorkoutsSessionSessionIdRoute,
  } as any)
const AuthenticatedWorkoutsSessionSessionIdDebriefRoute =
  AuthenticatedWorkoutsSessionSessionIdDebriefRouteImport.update({
    id: '/debrief',
    path: '/debrief',
    getParentRoute: () => AuthenticatedWorkoutsSessionSessionIdRoute,
  } as any)
const AuthenticatedWorkoutsSessionSessionIdBriefRoute =
  AuthenticatedWorkoutsSessionSessionIdBriefRouteImport.update({
    id: '/brief',
    path: '/brief',
    getParentRoute: () => AuthenticatedWorkoutsSessionSessionIdRoute,
  } as any)
const AuthenticatedWorkoutsSessionSessionIdExerciseExerciseIdRoute =
  AuthenticatedWorkoutsSessionSessionIdExerciseExerciseIdRouteImport.update({
    id: '/exercise/$exerciseId',
    path: '/exercise/$exerciseId',
    getParentRoute: () => AuthenticatedWorkoutsSessionSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ask': typeof AuthenticatedAskRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercises': typeof AuthenticatedExercisesRoute
  '/dev': typeof AuthenticatedDevRouteWithChildren
  '/export': typeof AuthenticatedExportRoute
  '/health': typeof AuthenticatedHealthRoute
  '/hydration': typeof AuthenticatedHydrationRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/meals': typeof AuthenticatedMealsRoute
  '/media-inbox': typeof AuthenticatedMediaInboxRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/shift': typeof AuthenticatedShiftRoute
  '/workout-templates': typeof AuthenticatedWorkoutTemplatesRoute
  '/workouts': typeof AuthenticatedWorkoutsRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dev/assets': typeof AuthenticatedDevAssetsRoute
  '/dev/characters': typeof AuthenticatedDevCharactersRoute
  '/dev/media': typeof AuthenticatedDevMediaRoute
  '/workout-session/$workoutId': typeof AuthenticatedWorkoutSessionWorkoutIdRoute
  '/workouts/history': typeof AuthenticatedWorkoutsHistoryRouteWithChildren
  '/workouts/program': typeof AuthenticatedWorkoutsProgramRoute
  '/dev/': typeof AuthenticatedDevIndexRoute
  '/workouts/': typeof AuthenticatedWorkoutsIndexRoute
  '/workouts/history/$sessionId': typeof AuthenticatedWorkoutsHistorySessionIdRoute
  '/workouts/session/$sessionId': typeof AuthenticatedWorkoutsSessionSessionIdRouteWithChildren
  '/workouts/session/$sessionId/brief': typeof AuthenticatedWorkoutsSessionSessionIdBriefRoute
  '/workouts/session/$sessionId/debrief': typeof AuthenticatedWorkoutsSessionSessionIdDebriefRoute
  '/workouts/session/$sessionId/summary': typeof AuthenticatedWorkoutsSessionSessionIdSummaryRoute
  '/workouts/session/$sessionId/': typeof AuthenticatedWorkoutsSessionSessionIdIndexRoute
  '/workouts/session/$sessionId/exercise/$exerciseId': typeof AuthenticatedWorkoutsSessionSessionIdExerciseExerciseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ask': typeof AuthenticatedAskRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercises': typeof AuthenticatedExercisesRoute
  '/export': typeof AuthenticatedExportRoute
  '/health': typeof AuthenticatedHealthRoute
  '/hydration': typeof AuthenticatedHydrationRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/meals': typeof AuthenticatedMealsRoute
  '/media-inbox': typeof AuthenticatedMediaInboxRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/shift': typeof AuthenticatedShiftRoute
  '/workout-templates': typeof AuthenticatedWorkoutTemplatesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dev/assets': typeof AuthenticatedDevAssetsRoute
  '/dev/characters': typeof AuthenticatedDevCharactersRoute
  '/dev/media': typeof AuthenticatedDevMediaRoute
  '/workout-session/$workoutId': typeof AuthenticatedWorkoutSessionWorkoutIdRoute
  '/workouts/history': typeof AuthenticatedWorkoutsHistoryRouteWithChildren
  '/workouts/program': typeof AuthenticatedWorkoutsProgramRoute
  '/dev': typeof AuthenticatedDevIndexRoute
  '/workouts': typeof AuthenticatedWorkoutsIndexRoute
  '/workouts/history/$sessionId': typeof AuthenticatedWorkoutsHistorySessionIdRoute
  '/workouts/session/$sessionId/brief': typeof AuthenticatedWorkoutsSessionSessionIdBriefRoute
  '/workouts/session/$sessionId/debrief': typeof AuthenticatedWorkoutsSessionSessionIdDebriefRoute
  '/workouts/session/$sessionId/summary': typeof AuthenticatedWorkoutsSessionSessionIdSummaryRoute
  '/workouts/session/$sessionId': typeof AuthenticatedWorkoutsSessionSessionIdIndexRoute
  '/workouts/session/$sessionId/exercise/$exerciseId': typeof AuthenticatedWorkoutsSessionSessionIdExerciseExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/capture': typeof AuthenticatedCaptureRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exercises': typeof AuthenticatedExercisesRoute
  '/_authenticated/dev': typeof AuthenticatedDevRouteWithChildren
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/hydration': typeof AuthenticatedHydrationRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/meals': typeof AuthenticatedMealsRoute
  '/_authenticated/media-inbox': typeof AuthenticatedMediaInboxRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/shift': typeof AuthenticatedShiftRoute
  '/_authenticated/workout-templates': typeof AuthenticatedWorkoutTemplatesRoute
  '/_authenticated/workouts': typeof AuthenticatedWorkoutsRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/dev/assets': typeof AuthenticatedDevAssetsRoute
  '/_authenticated/dev/characters': typeof AuthenticatedDevCharactersRoute
  '/_authenticated/dev/media': typeof AuthenticatedDevMediaRoute
  '/_authenticated/workout-session/$workoutId': typeof AuthenticatedWorkoutSessionWorkoutIdRoute
  '/_authenticated/workouts/history': typeof AuthenticatedWorkoutsHistoryRouteWithChildren
  '/_authenticated/workouts/program': typeof AuthenticatedWorkoutsProgramRoute
  '/_authenticated/dev/': typeof AuthenticatedDevIndexRoute
  '/_authenticated/workouts/': typeof AuthenticatedWorkoutsIndexRoute
  '/_authenticated/workouts/history/$sessionId': typeof AuthenticatedWorkoutsHistorySessionIdRoute
  '/_authenticated/workouts/session/$sessionId': typeof AuthenticatedWorkoutsSessionSessionIdRouteWithChildren
  '/_authenticated/workouts/session/$sessionId/brief': typeof AuthenticatedWorkoutsSessionSessionIdBriefRoute
  '/_authenticated/workouts/session/$sessionId/debrief': typeof AuthenticatedWorkoutsSessionSessionIdDebriefRoute
  '/_authenticated/workouts/session/$sessionId/summary': typeof AuthenticatedWorkoutsSessionSessionIdSummaryRoute
  '/_authenticated/workouts/session/$sessionId/': typeof AuthenticatedWorkoutsSessionSessionIdIndexRoute
  '/_authenticated/workouts/session/$sessionId/exercise/$exerciseId': typeof AuthenticatedWorkoutsSessionSessionIdExerciseExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/ask'
    | '/capture'
    | '/dashboard'
    | '/exercises'
    | '/dev'
    | '/export'
    | '/health'
    | '/hydration'
    | '/journal'
    | '/meals'
    | '/media-inbox'
    | '/nutrition'
    | '/profile'
    | '/progress'
    | '/shift'
    | '/workout-templates'
    | '/workouts'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/dev/assets'
    | '/dev/characters'
    | '/dev/media'
    | '/workout-session/$workoutId'
    | '/workouts/history'
    | '/workouts/program'
    | '/dev/'
    | '/workouts/'
    | '/workouts/history/$sessionId'
    | '/workouts/session/$sessionId'
    | '/workouts/session/$sessionId/brief'
    | '/workouts/session/$sessionId/debrief'
    | '/workouts/session/$sessionId/summary'
    | '/workouts/session/$sessionId/'
    | '/workouts/session/$sessionId/exercise/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/ask'
    | '/capture'
    | '/dashboard'
    | '/exercises'
    | '/export'
    | '/health'
    | '/hydration'
    | '/journal'
    | '/meals'
    | '/media-inbox'
    | '/nutrition'
    | '/profile'
    | '/progress'
    | '/shift'
    | '/workout-templates'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/dev/assets'
    | '/dev/characters'
    | '/dev/media'
    | '/workout-session/$workoutId'
    | '/workouts/history'
    | '/workouts/program'
    | '/dev'
    | '/workouts'
    | '/workouts/history/$sessionId'
    | '/workouts/session/$sessionId/brief'
    | '/workouts/session/$sessionId/debrief'
    | '/workouts/session/$sessionId/summary'
    | '/workouts/session/$sessionId'
    | '/workouts/session/$sessionId/exercise/$exerciseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/ask'
    | '/_authenticated/capture'
    | '/_authenticated/dashboard'
    | '/_authenticated/exercises'
    | '/_authenticated/dev'
    | '/_authenticated/export'
    | '/_authenticated/health'
    | '/_authenticated/hydration'
    | '/_authenticated/journal'
    | '/_authenticated/meals'
    | '/_authenticated/media-inbox'
    | '/_authenticated/nutrition'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/shift'
    | '/_authenticated/workout-templates'
    | '/_authenticated/workouts'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/dev/assets'
    | '/_authenticated/dev/characters'
    | '/_authenticated/dev/media'
    | '/_authenticated/workout-session/$workoutId'
    | '/_authenticated/workouts/history'
    | '/_authenticated/workouts/program'
    | '/_authenticated/dev/'
    | '/_authenticated/workouts/'
    | '/_authenticated/workouts/history/$sessionId'
    | '/_authenticated/workouts/session/$sessionId'
    | '/_authenticated/workouts/session/$sessionId/brief'
    | '/_authenticated/workouts/session/$sessionId/debrief'
    | '/_authenticated/workouts/session/$sessionId/summary'
    | '/_authenticated/workouts/session/$sessionId/'
    | '/_authenticated/workouts/session/$sessionId/exercise/$exerciseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workouts': {
      id: '/_authenticated/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthenticatedWorkoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workout-templates': {
      id: '/_authenticated/workout-templates'
      path: '/workout-templates'
      fullPath: '/workout-templates'
      preLoaderRoute: typeof AuthenticatedWorkoutTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shift': {
      id: '/_authenticated/shift'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof AuthenticatedShiftRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media-inbox': {
      id: '/_authenticated/media-inbox'
      path: '/media-inbox'
      fullPath: '/media-inbox'
      preLoaderRoute: typeof AuthenticatedMediaInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meals': {
      id: '/_authenticated/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AuthenticatedMealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hydration': {
      id: '/_authenticated/hydration'
      path: '/hydration'
      fullPath: '/hydration'
      preLoaderRoute: typeof AuthenticatedHydrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev': {
      id: '/_authenticated/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof AuthenticatedDevRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercises': {
      id: '/_authenticated/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AuthenticatedExercisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capture': {
      id: '/_authenticated/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AuthenticatedCaptureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workouts/': {
      id: '/_authenticated/workouts/'
      path: '/'
      fullPath: '/workouts/'
      preLoaderRoute: typeof AuthenticatedWorkoutsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkoutsRoute
    }
    '/_authenticated/dev/': {
      id: '/_authenticated/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof AuthenticatedDevIndexRouteImport
      parentRoute: typeof AuthenticatedDevRoute
    }
    '/_authenticated/workouts/program': {
      id: '/_authenticated/workouts/program'
      path: '/program'
      fullPath: '/workouts/program'
      preLoaderRoute: typeof AuthenticatedWorkoutsProgramRouteImport
      parentRoute: typeof AuthenticatedWorkoutsRoute
    }
    '/_authenticated/workouts/history': {
      id: '/_authenticated/workouts/history'
      path: '/history'
      fullPath: '/workouts/history'
      preLoaderRoute: typeof AuthenticatedWorkoutsHistoryRouteImport
      parentRoute: typeof AuthenticatedWorkoutsRoute
    }
    '/_authenticated/workout-session/$workoutId': {
      id: '/_authenticated/workout-session/$workoutId'
      path: '/workout-session/$workoutId'
      fullPath: '/workout-session/$workoutId'
      preLoaderRoute: typeof AuthenticatedWorkoutSessionWorkoutIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/media': {
      id: '/_authenticated/dev/media'
      path: '/media'
      fullPath: '/dev/media'
      preLoaderRoute: typeof AuthenticatedDevMediaRouteImport
      parentRoute: typeof AuthenticatedDevRoute
    }
    '/_authenticated/dev/characters': {
      id: '/_authenticated/dev/characters'
      path: '/characters'
      fullPath: '/dev/characters'
      preLoaderRoute: typeof AuthenticatedDevCharactersRouteImport
      parentRoute: typeof AuthenticatedDevRoute
    }
    '/_authenticated/dev/assets': {
      id: '/_authenticated/dev/assets'
      path: '/assets'
      fullPath: '/dev/assets'
      preLoaderRoute: typeof AuthenticatedDevAssetsRouteImport
      parentRoute: typeof AuthenticatedDevRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workouts/session/$sessionId': {
      id: '/_authenticated/workouts/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/workouts/session/$sessionId'
      preLoaderRoute: typeof AuthenticatedWorkoutsSessionSessionIdRouteImport
      parentRoute: typeof AuthenticatedWorkoutsRoute
    }
    '/_authenticated/workouts/history/$sessionId': {
      id: '/_authenticated/workouts/history/$sessionId'
      path: '/$sessionId'
      fullPath: '/workouts/history/$sessionId'
      preLoaderRoute: typeof AuthenticatedWorkoutsHistorySessionIdRouteImport
      parentRoute: typeof AuthenticatedWorkoutsHistoryRoute
    }
    '/_authenticated/workouts/session/$sessionId/': {
      id: '/_authenticated/workouts/session/$sessionId/'
      path: '/'
      fullPath: '/workouts/session/$sessionId/'
      preLoaderRoute: typeof AuthenticatedWorkoutsSessionSessionIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkoutsSessionSessionIdRoute
    }
    '/_authenticated/workouts/session/$sessionId/summary': {
      id: '/_authenticated/workouts/session/$sessionId/summary'
      path: '/summary'
      fullPath: '/workouts/session/$sessionId/summary'
      preLoaderRoute: typeof AuthenticatedWorkoutsSessionSessionIdSummaryRouteImport
      parentRoute: typeof AuthenticatedWorkoutsSessionSessionIdRoute
    }
    '/_authenticated/workouts/session/$sessionId/debrief': {
      id: '/_authenticated/workouts/session/$sessionId/debrief'
      path: '/debrief'
      fullPath: '/workouts/session/$sessionId/debrief'
      preLoaderRoute: typeof AuthenticatedWorkoutsSessionSessionIdDebriefRouteImport
      parentRoute: typeof AuthenticatedWorkoutsSessionSessionIdRoute
    }
    '/_authenticated/workouts/session/$sessionId/brief': {
      id: '/_authenticated/workouts/session/$sessionId/brief'
      path: '/brief'
      fullPath: '/workouts/session/$sessionId/brief'
      preLoaderRoute: typeof AuthenticatedWorkoutsSessionSessionIdBriefRouteImport
      parentRoute: typeof AuthenticatedWorkoutsSessionSessionIdRoute
    }
    '/_authenticated/workouts/session/$sessionId/exercise/$exerciseId': {
      id: '/_authenticated/workouts/session/$sessionId/exercise/$exerciseId'
      path: '/exercise/$exerciseId'
      fullPath: '/workouts/session/$sessionId/exercise/$exerciseId'
      preLoaderRoute: typeof AuthenticatedWorkoutsSessionSessionIdExerciseExerciseIdRouteImport
      parentRoute: typeof AuthenticatedWorkoutsSessionSessionIdRoute
    }
  }
}

interface AuthenticatedDevRouteChildren {
  AuthenticatedDevAssetsRoute: typeof AuthenticatedDevAssetsRoute
  AuthenticatedDevCharactersRoute: typeof AuthenticatedDevCharactersRoute
  AuthenticatedDevMediaRoute: typeof AuthenticatedDevMediaRoute
  AuthenticatedDevIndexRoute: typeof AuthenticatedDevIndexRoute
}

const AuthenticatedDevRouteChildren: AuthenticatedDevRouteChildren = {
  AuthenticatedDevAssetsRoute: AuthenticatedDevAssetsRoute,
  AuthenticatedDevCharactersRoute: AuthenticatedDevCharactersRoute,
  AuthenticatedDevMediaRoute: AuthenticatedDevMediaRoute,
  AuthenticatedDevIndexRoute: AuthenticatedDevIndexRoute,
}

const AuthenticatedDevRouteWithChildren =
  AuthenticatedDevRoute._addFileChildren(AuthenticatedDevRouteChildren)

interface AuthenticatedWorkoutsHistoryRouteChildren {
  AuthenticatedWorkoutsHistorySessionIdRoute: typeof AuthenticatedWorkoutsHistorySessionIdRoute
}

const AuthenticatedWorkoutsHistoryRouteChildren: AuthenticatedWorkoutsHistoryRouteChildren =
  {
    AuthenticatedWorkoutsHistorySessionIdRoute:
      AuthenticatedWorkoutsHistorySessionIdRoute,
  }

const AuthenticatedWorkoutsHistoryRouteWithChildren =
  AuthenticatedWorkoutsHistoryRoute._addFileChildren(
    AuthenticatedWorkoutsHistoryRouteChildren,
  )

interface AuthenticatedWorkoutsSessionSessionIdRouteChildren {
  AuthenticatedWorkoutsSessionSessionIdBriefRoute: typeof AuthenticatedWorkoutsSessionSessionIdBriefRoute
  AuthenticatedWorkoutsSessionSessionIdDebriefRoute: typeof AuthenticatedWorkoutsSessionSessionIdDebriefRoute
  AuthenticatedWorkoutsSessionSessionIdSummaryRoute: typeof AuthenticatedWorkoutsSessionSessionIdSummaryRoute
  AuthenticatedWorkoutsSessionSessionIdIndexRoute: typeof AuthenticatedWorkoutsSessionSessionIdIndexRoute
  AuthenticatedWorkoutsSessionSessionIdExerciseExerciseIdRoute: typeof AuthenticatedWorkoutsSessionSessionIdExerciseExerciseIdRoute
}

const AuthenticatedWorkoutsSessionSessionIdRouteChildren: AuthenticatedWorkoutsSessionSessionIdRouteChildren =
  {
    AuthenticatedWorkoutsSessionSessionIdBriefRoute:
      AuthenticatedWorkoutsSessionSessionIdBriefRoute,
    AuthenticatedWorkoutsSessionSessionIdDebriefRoute:
      AuthenticatedWorkoutsSessionSessionIdDebriefRoute,
    AuthenticatedWorkoutsSessionSessionIdSummaryRoute:
      AuthenticatedWorkoutsSessionSessionIdSummaryRoute,
    AuthenticatedWorkoutsSessionSessionIdIndexRoute:
      AuthenticatedWorkoutsSessionSessionIdIndexRoute,
    AuthenticatedWorkoutsSessionSessionIdExerciseExerciseIdRoute:
      AuthenticatedWorkoutsSessionSessionIdExerciseExerciseIdRoute,
  }

const AuthenticatedWorkoutsSessionSessionIdRouteWithChildren =
  AuthenticatedWorkoutsSessionSessionIdRoute._addFileChildren(
    AuthenticatedWorkoutsSessionSessionIdRouteChildren,
  )

interface AuthenticatedWorkoutsRouteChildren {
  AuthenticatedWorkoutsHistoryRoute: typeof AuthenticatedWorkoutsHistoryRouteWithChildren
  AuthenticatedWorkoutsProgramRoute: typeof AuthenticatedWorkoutsProgramRoute
  AuthenticatedWorkoutsIndexRoute: typeof AuthenticatedWorkoutsIndexRoute
  AuthenticatedWorkoutsSessionSessionIdRoute: typeof AuthenticatedWorkoutsSessionSessionIdRouteWithChildren
}

const AuthenticatedWorkoutsRouteChildren: AuthenticatedWorkoutsRouteChildren = {
  AuthenticatedWorkoutsHistoryRoute:
    AuthenticatedWorkoutsHistoryRouteWithChildren,
  AuthenticatedWorkoutsProgramRoute: AuthenticatedWorkoutsProgramRoute,
  AuthenticatedWorkoutsIndexRoute: AuthenticatedWorkoutsIndexRoute,
  AuthenticatedWorkoutsSessionSessionIdRoute:
    AuthenticatedWorkoutsSessionSessionIdRouteWithChildren,
}

const AuthenticatedWorkoutsRouteWithChildren =
  AuthenticatedWorkoutsRoute._addFileChildren(
    AuthenticatedWorkoutsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedCaptureRoute: typeof AuthenticatedCaptureRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExercisesRoute: typeof AuthenticatedExercisesRoute
  AuthenticatedDevRoute: typeof AuthenticatedDevRouteWithChildren
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedHydrationRoute: typeof AuthenticatedHydrationRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedMealsRoute: typeof AuthenticatedMealsRoute
  AuthenticatedMediaInboxRoute: typeof AuthenticatedMediaInboxRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedShiftRoute: typeof AuthenticatedShiftRoute
  AuthenticatedWorkoutTemplatesRoute: typeof AuthenticatedWorkoutTemplatesRoute
  AuthenticatedWorkoutsRoute: typeof AuthenticatedWorkoutsRouteWithChildren
  AuthenticatedWorkoutSessionWorkoutIdRoute: typeof AuthenticatedWorkoutSessionWorkoutIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedCaptureRoute: AuthenticatedCaptureRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExercisesRoute: AuthenticatedExercisesRoute,
  AuthenticatedDevRoute: AuthenticatedDevRouteWithChildren,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedHydrationRoute: AuthenticatedHydrationRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedMealsRoute: AuthenticatedMealsRoute,
  AuthenticatedMediaInboxRoute: AuthenticatedMediaInboxRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedShiftRoute: AuthenticatedShiftRoute,
  AuthenticatedWorkoutTemplatesRoute: AuthenticatedWorkoutTemplatesRoute,
  AuthenticatedWorkoutsRoute: AuthenticatedWorkoutsRouteWithChildren,
  AuthenticatedWorkoutSessionWorkoutIdRoute:
    AuthenticatedWorkoutSessionWorkoutIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
